name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.1.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        FOLDER: build
