name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Test
      run: |
        yarn install
        yarn tsc
        CI=true yarn test

    - name: Cypress run
      uses: cypress-io/github-action@v1
      with:
        # Linux and MacOS
        start: yarn start
        # Takes precedences on Windows
        start-windows: yarn run start:windows:server
      env:
        CYPRESS_baseUrl: http://10.1.0.4:3000

    - name: Build
      run: |
        yarn install
        yarn run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
